---
dist: xenial
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/openstackclient
  matrix:
    - VERSION=ocata BUILD_OPTS="--build-arg=UBUNTU_RELEASE=16.04"
    - VERSION=pike BUILD_OPTS="--build-arg=UBUNTU_RELEASE=16.04"
    - VERSION=queens BUILD_OPTS="--build-arg=UBUNTU_RELEASE=16.04"
    - VERSION=rocky BUILD_OPTS="--build-arg=UBUNTU_RELEASE=18.04"
    - VERSION=stein BUILD_OPTS="--build-arg=UBUNTU_RELEASE=18.04"
    - VERSION=train BUILD_OPTS="--build-arg=UBUNTU_RELEASE=18.04"

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
